twitter-to-kafka-service:
  twitter-Keyword:
    - java
    - Microservice
    - Spring
    - Kafka
    - Elasticsearch
  enable-mock-tweets: true
  mock-min-tweets-length: 5
  mock-max-tweets-length: 15
  mock-sleep-ms: 10000